###
GET http://localhost:8080/todo

<> 2023-12-25T133929.200.json

###
GET http://localhost:8080/todo/2

<> 2023-12-25T133953.404.json

###
POST http://localhost:8080/todo
Content-Type: application/json

{
  "id": 102,
  "description":,
  "duedate": "2024-01-01T16:00:00",
  "priority": 5
}

###
PUT http://localhost:8080/todo/111
Content-Type: application/json

{
  "id": 101,
  "description": "Complete Frontend",
  "duedate": "2024-01-01T16:00:00",
  "priority": 12
}

###
DELETE http://localhost:8080/todo/33
